language: php

php:
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS zurmo_test;" -uroot; fi

#script: phpunit --configuration phpunit_$DB.xml --coverage-text
script: phpunit --coverage-text app/protected/test/unit/TestSuite.php All

#notifications:
#  irc: "irc.freenode.org#travis"