language: php

php:
  - 5.4
  - 5.5

services:
  - memcached

env:
  - DB=mysql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-imap php5-mysql php5-memcache php5-curl php-apc php-soap php5-gd

before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS zurmo_test;" -uroot; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS zurmo_temp;" -uroot; fi
  - phpenv config-add testScript/myconfig.ini
  - mysql -e 'create database zurmo_test;'
  - mysql -e 'create database zurmo_temp;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - chmod +x testScript/testScript.sh
  - testScript/testScript.sh


#script: phpunit --configuration phpunit_$DB.xml --coverage-text
script:
  - cd app/protected/tests/unit
#  - phpunit --coverage-text TestSuite.php All
  - phpunit TestSuite.php mashableInbox

#notifications:
#  irc: "irc.freenode.org#travis"